clone_folder: c:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt4
    - qt: qt5

install:
  - cd ..
  - appveyor DownloadFile http://omega.gg/get/Sky/3rdparty/win32 -FileName 3rdparty.zip
  - 7z x 3rdparty.zip
  - git clone https://github.com/omega-gg/Sky
  - cd Sky
  - sh configure.sh %qt% win32
  - cd ../MotionBox
  - sh configure.sh %qt% win32

build_script:
  - sh build.sh %qt% win32 deploy
