sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      env: QT=qt4 TARGET=i386
    - os: linux
      env: QT=qt4 TARGET=amd64
    - os: linux
      env: QT=qt5 TARGET=i386
    - os: linux
      env: QT=qt5 TARGET=amd64

script:
  - docker run -d --name ubuntu -v $PWD:/MotionBox ${TARGET}/ubuntu:18.04 tail -f /dev/null
  - docker exec -t ubuntu bash -c "cd /MotionBox;
                                   apt-get update;
                                   apt-get -y install sudo curl git;
                                   sh environment.sh mingw ${QT};
                                   sh build.sh linux all"
